name: example
description: Example.
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  dfunc: ^0.3.1

dev_dependencies:
  build_runner: ^1.0.0
  dfunc_builder: ^0.0.1
  pedantic: ^1.7.0
  test: ^1.6.0
