name: dfunc
description: Functional batteries for Dart. Inspired by functional javascript libraries such as ramda.js or lodash.
version: 0.1.0
homepage: https://github.com/ookami-kb/dfunc

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
