name: dfunc
description: Functional batteries for Dart. Implementation of Either, Optional etc.
version: 0.5.0
homepage: https://github.com/ookami-kb/dfunc

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.1
  test: ^1.16.0-nullsafety.5
