name: dfunc_builder
description: Builder for dfunc package. This package does nothing without dfunc.
version: 0.0.1
homepage: https://github.com/ookami-kb/dfunc

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.4
  build: '>=0.12.6 <2.0.0'
  build_runner: ^1.0.0
  source_gen: ^0.9.4+7
  collection: ^1.14.12
  dfunc: '>=0.3.1 <0.4.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
